config/routes.rb
Rails.application.routes.draw do
  resources :regles
  resources :notes
  resources :messages
  resources :salves
  resources :topics
  devise_for :users
  root 'home#index'

  get 'home/private'
  get 'topics/mine', to: 'topics#mine', as: 'mine'

  match "/participate" => "participation#participate", :via => :post, :as => :participate
  match "/salve" => "salves#finish", :via => :post, :as => :finish
  match "/take_salve" => "salves#take_salve", :via => :post, :as => :take_salve
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :salve
  has_many :notes, :dependent => :destroy

  validates :content, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  # POST /messages
  # POST /messages.json
  def create
    if valid_salve(message_params[:topic_id], current_user.id, message_params[:salve_id])
      nb_messages = messages_in_topic(message_params[:topic_id], current_user)
      message_name = current_user.username[0] + nb_messages.to_s
      @message = Message.new(user_id: current_user.id,
                             salve_id: message_params[:salve_id],
                             content: message_params[:content],
                             url: message_params[:url],
                             name: message_name,
                             location: message_params[:location])
      if @message.save
        @note = Note.new(user_id: current_user.id,
                         message_id: @message.id,
                         value: message_params[:note_value].to_i)
        if @note.save
          redirect_to topic_path(message_params[:topic_id]), notice: 'Proposition envoyée.'
        else
          redirect_to topic_path(message_params[:topic_id]), alert: 'Note invalide.'
        end
      else
        redirect_to topic_path(message_params[:topic_id]), alert: 'Message invalide.'
      end
    else
      redirect_to root_path, alert: "Salve invalide"
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:user_id, :salve_id, :content, :name, :url, :location, :topic_id, :note_value)
  end

  # Get the total messages throught salves of a user in a topic
  def messages_in_topic (topic_id, user)
    @salvesuser = Salve.where(topic_id: topic_id, user_id: user.id)
    @nb_messages = 1
    @salvesuser.each do |salve|
      @nb_messages += salve.messages.count
    end
    return @nb_messages
  end

  def valid_salve(topic, user, salve)
    salve = Salve.where(id: salve, topic_id: topic, user_id: user, finished: true).first
    salve.blank?
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
    <%= form_with(model: message, local: true) do |form| %>
      <% if message.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

          <ul>
            <% message.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form.hidden_field :topic_id, :value => @topic.id %>
      <%= form.hidden_field :salve_id, :value => @topic.salves.last.id %>

      <div class="form-group">
        <%= form.text_area :content, placeholder: "Ajouter une proposition...", :class => "form-control" %>
        <small id="valueHelp" class="form-text text-muted">
          * Une proposition ne peut plus être modifiée une fois validée
        </small>
      </div>

      <div class="form-group">
        <div class="form-row">
          <div class="col-md-2">
            <div class="input-group">
              <%= form.number_field :note_value, placeholder: "Estimez..", :class => "form-control" %>
              <div class="input-group-append">
                <span class="input-group-text" id="basic-addon2">%</span>
              </div>
            </div>
          </div>
          <div class="col">
            <%= form.text_field :url, placeholder: "Lien URL vers un média (vidéo, page internet...)", :class => "form-control" %>
          </div>
          <div class="col-md-4">
            <%= form.text_field :location, placeholder: "Préciser où regarder (ligne, timecode...)", :class => "form-control" %>
          </div>
        </div>
      </div>


        <div class="form-row">
          <div class="col">
            <%= form.submit "Valider ma proposition", :class => 'btn btn-dark btn-block' %>
          </div>
          <div class="col">
            <%= link_to "Terminer ma salve", finish_path({user: current_user, topic: @topic, salve: @topic.salves.last}), method: :post, class: "btn btn-outline-dark btn-block" %>
          </div>
        </div>


    <% end %>

app/views/messages/_message.html.erb
<% @current_message = message %>

<p class="card-text"><strong>#<%= message.name %></strong> - <%= message.content %>
  <% if !message.url.blank? %>
    <a href="<%= message.url %>" target="_blank" data-toggle="tooltip" title="Lien vers <%= message.url %>">
      <span class="badge badge-info">
      Lien vers le media <% if !message.location.blank? %> (<%= message.location %>) <% end %>
      </span>
    </a>
  <% end %>

  <div class="form-group row align-items-center">
    <div class="col-4 col-md-2">
      <%= ma_note message %>
    </div>
    <div class="col">
      <%= render autre_notes message %>
    </div>
  </div>
  <% if !message_iteration.last? %>
  <hr/>
  <% end %>
</p>