config/routes.rb
Rails.application.routes.draw do
  resources :regles
  resources :notes
  resources :messages
  resources :salves
  resources :topics
  devise_for :users
  root 'home#index'

  get 'home/private'
  get 'topics/mine', to: 'topics#mine', as: 'mine'

  match "/participate" => "participation#participate", :via => :post, :as => :participate
  match "/salve" => "salves#finish", :via => :post, :as => :finish
  match "/take_salve" => "salves#take_salve", :via => :post, :as => :take_salve
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :salves, :dependent => :destroy
  has_many :participations, :dependent => :destroy

  def ma_salve(user, salve)
    user.id == salve.user.id
  end

  def je_participe(user, topic)
    Participation.where(user_id: user.id, topic_id: topic.id).exists?
  end

  def last_salve(user, last_salve)
    user.id == last_salve.user.id
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  protect_from_forgery

  # Only for members
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :mine, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  def mine
    @topics = Topic.joins(:participation).where(participation: { status: true, user_id: current_user.id })
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @regles = Regle.all
    @salves = @topic.salves.order('created_at ASC')
    @message = Message.new
    @note = Note.new
    session[:return_to] ||= request.referer
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(title: topic_params[:title], user_id: current_user.id, finished: false, description: topic_params[:description])
    if @topic.save
      @salve = Salve.new(user_id: current_user.id, topic_id: @topic.id, finished: false)
      @participate = Participation.new(user_id: current_user.id, topic_id: @topic.id, status: true)
      if @salve.save && @participate.save
        redirect_to @topic, notice: 'Redico créé, bon débat !'
      end
    end

  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html {redirect_to @topic, notice: 'Topic was successfully updated.'}
        format.json {render :show, status: :ok, location: @topic}
      else
        format.html {render :edit}
        format.json {render json: @topic.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    redirect_to topics_url, notice: 'Topic was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_topic
    @topic = Topic.find(params[:id])
    @user = current_user.id
  rescue ActiveRecord::RecordNotFound
    redirect_to root_url, :flash => { :alert => "Record not found." }
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def topic_params
    params.require(:topic).permit(:title, :description)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  # Helpers pour la page topics/show.html.erb

  # Si l'utilisateur courant est en train de salver
  def je_salve
    salves = @topic.salves.order('created_at ASC')
    @topic.ma_salve(current_user, salves.last)
  end

  # Si l'utilisateur courant est un participant de la salve visitée actuellement
  def je_participe
    @topic.je_participe(current_user, @topic)
  end

  # Si personne ne salve dans le redico visité actuellement
  def personne_ne_salve
    Salve.where(topic_id: @topic, finished: false).first.blank?
  end

  # Renvoie les participants du redico visité actuellement
  def participants
    Participation.where(topic_id: @topic.id)
  end

  # Verifie si c'est l'utilisateur courrant qui a salvé en dernier
  def jai_salve_en_dernier
    salves = @topic.salves.order('created_at ASC')
    if @topic.salves.count > 1
      @topic.last_salve(current_user, salves.offset(1).last)
    else
      @topic.last_salve(current_user, salves.last)
    end
  end

  # Si j'ai pas note, ajoute un formulaire pour le faire
  def ma_note message
    @note = Note.where(message_id: message.id, user_id: current_user.id).first
    if !@note.blank?
      render 'notes/form', note: @note
    else
      render 'notes/form', note: Note.new
    end
  end

  # Récupère toutes les autres notes d'un message
  def autre_notes message
    Note.where(message_id: message.id).where.not(user_id: current_user.id)
  end
end

app/views/topics/_form.html.erb
<div class="card">
  <div class="card-body">

    <%= form_with(model: topic, local: true) do |form| %>
      <% if topic.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

          <ul>
            <% topic.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, :class => "form-control", :placeholder => "Nom de votre redico" %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, :class => "form-control", :placeholder => "Description rapide de votre redico..." %>
      </div>

      <%= form.submit "Valider", :class => 'btn btn-info btn-block' %>

    <% end %>

  </div>
</div>
<br/>

app/views/topics/_topic.html.erb
<div class="col-sm-6">
  <div class="card">
    <div class="card-header">
      <%= topic.title %> <span class="badge badge-secondary"> <%= topic.finished? ? "Terminé" : "En cours" %> </span> <br/>
      <small>Proposé par : <strong><%= topic.user.login %></strong>, <%= time_ago_in_words(topic.created_at) %> </small>
      <p class="float-right">
        <%= link_to '<span aria-hidden="true">&times;</span>'.html_safe, topic, class: "close", method: :delete, data: {confirm: 'Are you sure?'} %>
      </p>
    </div>
    <div class="card-body">
      <blockquote class="blockquote">
        <p class="lead"><%= topic.description %></p>
      </blockquote>
    </div>
    <div class="card-footer text-muted">
      <%= link_to "Découvrir", topic, class: "btn btn-block btn-secondary" %>
    </div>
  </div>
  <br/>
</div>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1 class="title">Liste des Redico</h1>

<hr/>

<div class="row">
  <%= render @topics %>
</div>

app/views/topics/mine.html.erb
<h1 class="title">Mes Redico</h1>

<hr/>

<div class="row">
  <%= render @topics %>
</div>

app/views/topics/new.html.erb
<h1 class="title">Créer un Redico</h1>

<div class="box">
  <%= render 'form', topic: @topic %>
</div>

app/views/topics/show.html.erb
<% content_for :title, @topic.title %>

<%= render partial: "topics/partials/presentation" %>

<h4 class="text-center">
  Règles :
<% @regles.each do |regle| %>
  <span class="badge badge-secondary" data-toggle="tooltip" title="<%= regle.content %>">#<%= regle.num %></span>
<% end %>
</h4>
<br/>
<% if !@salves.first.messages.blank? %>
  <%= render @salves %>
<% else %>
  <div class="card">
    <div class="card-body">
      Pas encore de messages dans ce Redico... cela ne devrait pas tarder !
    </div>
  </div>
  <br/>
<% end %>

<% if je_participe %>

  <% if personne_ne_salve %>
    <div class="card">
      <div class="card-body">
        <h5>
          <span class="badge badge-secondary">
            Personne ne salve
          </span>
        </h5>
        <% if jai_salve_en_dernier %>
          <span>En attente d'un participant...</span>
          <%= link_to "Rafraîchir la page", topic_path(@topic, anchor: "refresh"), id: "refresh", class: "btn btn-outline-secondary btn-block" %>
        <% else %>
          <%= link_to "Je prend le relais", take_salve_path({user: current_user, topic: @topic}), method: :post, class: "btn btn-secondary btn-block" %>
        <% end %>

      </div>
    </div>

  <% elsif je_salve %>
    <div class="card">
      <div class="card-body">
        <h5>
          <span class="badge badge-secondary">
            C'est à vous de salver !
          </span>
        </h5>
        <%= render '/messages/form', message: @message %>
      </div>
    </div>

  <% else %>
    <div class="card">
      <div class="card-body">
        <h5>
          <span class="badge badge-secondary">
            C'est au tour de <%= @salves.last.user.login %>
          </span>
        </h5>
        <span><%= @salves.last.user.login %> est en train de salver...</span>
        <%= link_to "Rafraîchir la page", topic_path(@topic, anchor: "refresh"), id: "refresh", class: "btn btn-outline-secondary btn-block" %>
      </div>
    </div>
  <% end %>

<% else %>
  <hr/>

      <%= link_to "Participer à ce Redico", participate_path({user: current_user, topic: @topic}), method: :post, class: "btn btn-secondary btn-block" %>

<% end %>