config/routes.rb
Rails.application.routes.draw do
  resources :regles
  resources :notes
  resources :messages
  resources :salves
  resources :topics
  devise_for :users
  root 'home#index'

  get 'home/private'
  get 'topics/mine', to: 'topics#mine', as: 'mine'

  match "/participate" => "participation#participate", :via => :post, :as => :participate
  match "/salve" => "salves#finish", :via => :post, :as => :finish
  match "/take_salve" => "salves#take_salve", :via => :post, :as => :take_salve
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/regle.rb
class Regle < ApplicationRecord
end

app/controllers/regles_controller.rb
class ReglesController < ApplicationController
  before_action :set_regle, only: [:show, :edit, :update, :destroy]

  # GET /regles
  # GET /regles.json
  def index
    @regles = Regle.all
  end

  # GET /regles/1
  # GET /regles/1.json
  def show
  end

  # GET /regles/new
  def new
    @regle = Regle.new
  end

  # GET /regles/1/edit
  def edit
  end

  # POST /regles
  # POST /regles.json
  def create
    @regle = Regle.new(regle_params)

    respond_to do |format|
      if @regle.save
        format.html { redirect_to @regle, notice: 'Regle was successfully created.' }
        format.json { render :show, status: :created, location: @regle }
      else
        format.html { render :new }
        format.json { render json: @regle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regles/1
  # PATCH/PUT /regles/1.json
  def update
    respond_to do |format|
      if @regle.update(regle_params)
        format.html { redirect_to @regle, notice: 'Regle was successfully updated.' }
        format.json { render :show, status: :ok, location: @regle }
      else
        format.html { render :edit }
        format.json { render json: @regle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regles/1
  # DELETE /regles/1.json
  def destroy
    @regle.destroy
    respond_to do |format|
      format.html { redirect_to regles_url, notice: 'Regle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regle
      @regle = Regle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def regle_params
      params.require(:regle).permit(:num, :content)
    end
end

app/helpers/regles_helper.rb
module ReglesHelper
end

app/views/regles/_form.html.erb
<%= form_with(model: regle, local: true) do |form| %>
  <% if regle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(regle.errors.count, "error") %> prohibited this regle from being saved:</h2>

      <ul>
        <% regle.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :num %>
    <%= form.number_field :num %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/regles/_regle.html.erb
<div class="card">
  <div class="card-body">
    <h2 class="display-6">Loi #<%= regle.num %></h2>
    <p class="lead"><%= regle.content %></p>
  </div>
</div>
<br/>

app/views/regles/edit.html.erb
<h1>Editing Regle</h1>

<%= render 'form', regle: @regle %>

<%= link_to 'Show', @regle %> |
<%= link_to 'Back', regles_path %>

app/views/regles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Règles du Redico <%= link_to "[source]", "https://www.sceptiques.qc.ca/forum/redico" %></h1>
<hr/>
<%= render @regles %>

app/views/regles/new.html.erb
<h1>New Regle</h1>

<%= render 'form', regle: @regle %>

<%= link_to 'Back', regles_path %>

app/views/regles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Num:</strong>
  <%= @regle.num %>
</p>

<p>
  <strong>Content:</strong>
  <%= @regle.content %>
</p>

<%= link_to 'Edit', edit_regle_path(@regle) %> |
<%= link_to 'Back', regles_path %>